COT_MAPPING = {
    "EURUSD": "099741",
    "GBPUSD": "096742",
    "USDJPY": "097741",
    "XAUUSD": "088691"
}

TWELVEDATA_MAPPING = {
    "EURUSD": "OANDA:EUR_USD",
    "GBPUSD": "OANDA:GBP_USD",
    "USDJPY": "OANDA:USD_JPY",
    "XAUUSD": "OANDA:XAU_USD"
}
